import React from 'react';
import { Intro, Intro_Duration, Intro_Edited } from './Intro';
import { Lack_Of_Narrative, Lack_Of_Narrative_Duration, Lack_Of_Narrative_Edited } from './Lack_Of_Narrative';
import { Repetitive_Structure, Repetitive_Structure_Duration, Repetitive_Structure_Edited } from './Repetitive_Structure';
import { Simple_Humor, Simple_Humor_Duration, Simple_Humor_Edited } from './Simple_Humor';
import { Target_Audience_Misalignment, Target_Audience_Misalignment_Duration, Target_Audience_Misalignment_Edited } from './Target_Audience_Misalignment';
import { Conclusion, Conclusion_Duration, Conclusion_Edited } from './Conclusion';
import { Ending, Ending_Duration, Ending_Edited } from './Ending';
let files = [{name: Intro, duration: Intro_Duration, edited: Intro_Edited }, {name: Lack_Of_Narrative, duration: Lack_Of_Narrative_Duration, edited: Lack_Of_Narrative_Edited }, {name: Repetitive_Structure, duration: Repetitive_Structure_Duration, edited: Repetitive_Structure_Edited }, {name: Simple_Humor, duration: Simple_Humor_Duration, edited: Simple_Humor_Edited }, {name: Target_Audience_Misalignment, duration: Target_Audience_Misalignment_Duration, edited: Target_Audience_Misalignment_Edited }, {name: Conclusion, duration: Conclusion_Duration, edited: Conclusion_Edited }, {name: Ending, duration: Ending_Duration, edited: Ending_Edited }];
export default files;
