import React from 'react';
import { Intro, Intro_Duration, Intro_Edited } from './Intro';
import { Early_Life_And_Rise, Early_Life_And_Rise_Duration, Early_Life_And_Rise_Edited } from './Early_Life_And_Rise';
import { Goal_Scoring_Prowess, Goal_Scoring_Prowess_Duration, Goal_Scoring_Prowess_Edited } from './Goal_Scoring_Prowess';
import { Major_Trophies_And_Individual_Awards, Major_Trophies_And_Individual_Awards_Duration, Major_Trophies_And_Individual_Awards_Edited } from './Major_Trophies_And_Individual_Awards';
import { Longevity_And_Adaptability, Longevity_And_Adaptability_Duration, Longevity_And_Adaptability_Edited } from './Longevity_And_Adaptability';
import { Impact_And_Influence, Impact_And_Influence_Duration, Impact_And_Influence_Edited } from './Impact_And_Influence';
import { Conclusion, Conclusion_Duration, Conclusion_Edited } from './Conclusion';
let files = [{name: Intro, duration: Intro_Duration, edited: Intro_Edited }, {name: Early_Life_And_Rise, duration: Early_Life_And_Rise_Duration, edited: Early_Life_And_Rise_Edited }, {name: Goal_Scoring_Prowess, duration: Goal_Scoring_Prowess_Duration, edited: Goal_Scoring_Prowess_Edited }, {name: Major_Trophies_And_Individual_Awards, duration: Major_Trophies_And_Individual_Awards_Duration, edited: Major_Trophies_And_Individual_Awards_Edited }, {name: Longevity_And_Adaptability, duration: Longevity_And_Adaptability_Duration, edited: Longevity_And_Adaptability_Edited }, {name: Impact_And_Influence, duration: Impact_And_Influence_Duration, edited: Impact_And_Influence_Edited }, {name: Conclusion, duration: Conclusion_Duration, edited: Conclusion_Edited }];
export default files;
